import type { Metadata } from "next";
import "./globals.css";
import { Orbitron, Inter } from "next/font/google"
import NavBar from "./_components/NavBar";

const orbitron = Orbitron({
  subsets: ["latin"],
  // This generates a CSS variable named --font-orbitron
  variable: "--font-orbitron",
});

const inter = Inter({
  subsets: ["latin"],
  // This generates a CSS variable named --font-orbitron
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "frontend",
  description: "Generated by create-prisma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${orbitron.variable} ${inter.variable}`}>
      <body>      <NavBar />{children}</body>
    </html>
  );
}
